name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Meson and Ninja
      run: |
        pip install -U pip
        pip install meson ninja

    - name: Configure and build
      run: |
        meson setup builddir
        meson compile -C builddir

    - name: Run tests
      run: meson test -C builddir --verbose
